config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("medlab/", admin.site.urls),
    # path('admin/', include('admin_black.urls')),
    path("", include("med.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    handler404 = "med.handlers.handler_404"

med/urls.py
from django.urls import path
from med.views import (
    HomeView,
    AboutView,
    DoctorView,
    PatientView,
    patient_create,
    doctor_view,
    Acceptance,
    LoginView,
    UserLogoutView,
    ServicesView,
    DepartmentView, Contact,
)

app_name = "med"
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("about/", AboutView.as_view(), name="about"),
    path("doctor/", DoctorView.as_view(), name="doctor"),
    path("bemor/", PatientView.as_view(), name="bemor"),
    path("patient/create/", patient_create, name="create-patient"),
    path("appoint/", doctor_view, name="appoint"),
    path("acceptance/list/", Acceptance.as_view(), name="acceptance"),
    path("services/", ServicesView.as_view(), name="services"),
    path("medilab/department/", DepartmentView.as_view(), name="department"),
    path('medilab/contact/', Contact.as_view(), name="contact"),
]

med/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import (
    Model,
    IntegerField,
    CharField,
    TextChoices,
    TextField,
    ManyToManyField,
    ImageField,
    ForeignKey,
    CASCADE,
    DateField,
)


# class User(AbstractUser):
#     pass


class Gender(TextChoices):
    MALE = "Male", "male"
    FEMALE = "Female", "female"


class Count(Model):
    doctor = IntegerField(default=0)
    departments = IntegerField(default=0)
    labs = IntegerField(default=0)
    awards = IntegerField(default=0)

    def __str__(self):
        return str(self.doctor)


class Disease(Model):
    title = CharField(max_length=128)

    def __str__(self):
        return self.title


class Patient(Model):
    fullname = CharField(max_length=128)
    age = IntegerField()
    gender = CharField(max_length=6, choices=Gender.choices, null=True)
    disease_id = ForeignKey(Disease, CASCADE, related_name="patients")

    def __str__(self):
        return self.fullname


class Icon(Model):
    name = CharField(max_length=128)
    link = CharField(max_length=128)

    def __str__(self):
        return self.name


class Doctor(Model):
    fullname = CharField(max_length=128)
    foto = ImageField(upload_to="media/", default="media/default.jpg")
    job = CharField(max_length=128)
    body = TextField()
    # icon = ManyToManyField(Icon, related_name="doctor", null=True)
    link = CharField(max_length=128)

    def __str__(self):
        return self.fullname


class PatientDoctor(Model):
    name = CharField(max_length=128)
    age = IntegerField()
    sickness = TextField(null=True)
    doctor = ForeignKey(Doctor, CASCADE, related_name="doctors")
    appointment_date = DateField()

    def __str__(self):
        return self.name


class Department(Model):
    title = CharField(max_length=128)
    description = TextField()
    body = TextField()
    image = ImageField(upload_to="media/", default="media/default.jpg")

    def __str__(self):
        return self.title

med/forms.py
from django.forms import ModelForm, Form, CharField, PasswordInput
from django import forms
from med.models import Patient, PatientDoctor


class PatientCreateForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            if str(field) != "is_active":
                self.fields[field].widget.attrs.update(
                    {"class": "form-control", "placeholder": f"Enter the {str(field)}"}
                )

    class Meta:
        model = Patient
        fields = ("fullname", "age", "gender", "disease_id")


class PatientForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            if str(field) != "is_active":
                self.fields[field].widget.attrs.update(
                    {"class": "form-control", "placeholder": f"Enter the {str(field)}"}
                )

    class Meta:
        model = PatientDoctor
        fields = ("name", "age", "sickness", "doctor", "appointment_date")
        widgets = {"appointment_date": forms.DateInput(attrs={"type": "date"})}


class UserLoginForm(Form):
    username = CharField(max_length=128)
    password = CharField(max_length=128, widget=PasswordInput)

med/views.py
from django.contrib import messages
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, TemplateView

from med.forms import PatientCreateForm, PatientForm, UserLoginForm
from med.models import Count, Doctor, Patient, PatientDoctor, Department


class HomeView(TemplateView):
    template_name = "index.html"


class AboutView(TemplateView):
    template_name = "med/about.html"


class DoctorView(ListView):
    model = Doctor
    template_name = "med/doctor.html"
    context_object_name = "doctor"


class PatientView(ListView):
    paginate_by = 20
    model = Patient
    template_name = "med/patient.html"
    context_object_name = "bemor"


@login_required()
def patient_create(request):
    if request.method == "POST":
        form = PatientCreateForm(request.POST)
        if form.is_valid():
            patient = Patient(
                fullname=form.cleaned_data["fullname"],
                age=form.cleaned_data["age"],
                gender=form.cleaned_data["gender"],
                disease_id=form.cleaned_data["disease_id"],
            )
            patient.save()
            messages.success(request, "Bemor mufafiqiyatli qo'shildi")
            return redirect(reverse("med:bemor"))
        else:
            return render(request, "med/patient_form.html", {"form": form})
    else:
        form = PatientCreateForm()
        return render(request, "med/patient_form.html", {"form": form})


def doctor_view(request):
    if request.method == "POST":
        form = PatientForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = PatientForm()
    return render(request, "med/appoint.html", {"form": form})


class Acceptance(ListView):
    model = PatientDoctor
    template_name = "med/acceptance.html"
    context_object_name = "acceptance"


class UserLogoutView(View):
    def get(self, request):
        logout(request)
        messages.success(request, "User successfully loged out")
        return redirect("med:home")


class LoginView(View):
    def get(self, request):
        form = UserLoginForm()
        return render(request, "user/login.html", {"form": form})

    def post(self, request):
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f"you have login as {username}")
                return redirect("med:home")
            else:
                messages.error(request, "Wrong username or password")
                return render(request, "user/login.html", {"form": form})
        else:
            return render(request, "user/login.html", {"form": form})


class ServicesView(TemplateView):
    template_name = "med/services.html"


class DepartmentView(ListView):
    model = Department
    template_name = "med/departments.html"
    context_object_name = "departments"


class Contact(TemplateView):
    template_name = "med/contact.html"

templates/med/about.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    {% include 'topbar.html' %}
    <header id="header" class="fixed-top">
        <div class="container d-flex align-items-center">
            <h1 class="logo me-auto"><a href="{% url 'med:home' %}" class="logo me-auto"><img
                    src="{% static 'assets/img/favicon1.png' %}" alt="" class="img-fluid"> Medilab</a></h1>
            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul>
                    {% if request.user.is_authenticated %}
                        <li><a class="nav-link scrollto" href="{% url 'med:acceptance' %}">Qabul</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:bemor' %}">Bemor</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:create-patient' %}">Bemor Qo'shish</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:logout' %}">Logout</a></li>
                    {% else %}
                        <li><a class="nav-link scrollto" href="{% url 'med:home' %}">Home</a></li>
                        <li><a class="nav-link scrollto active" href="{% url 'med:about' %}">About</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:services' %}">Services</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:department' %}">Departments</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:doctor' %}">Doctors</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:contact' %}">Contact</a></li>
                        <li><a href="{% url 'med:appoint' %}" class="nav-link scrollto"><span
                                class="d-none d-md-inline">Make an Appointment</span>
                        </a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:login' %}">Login</a></li>
                    {% endif %}
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav>
        </div>
    </header>
    <br>
    <!-- ======= About Section ======= -->
    <section id="about" class="about">
        <div class="container-fluid">

            <div class="row">
                <div class="col-xl-5 col-lg-6 video-box d-flex justify-content-center align-items-stretch position-relative">
                    <a href="https://www.youtube.com/watch?v=H62N2dNcZeA" class="glightbox play-btn mb-4"></a>
                </div>

                <div class="col-xl-7 col-lg-6 icon-boxes d-flex flex-column align-items-stretch justify-content-center py-5 px-lg-5">
                    <h3>Enim quis est voluptatibus aliquid consequatur fugiat</h3>
                    <p>Esse voluptas cumque vel exercitationem. Reiciendis est hic accusamus. Non ipsam et sed minima
                        temporibus laudantium. Soluta voluptate sed facere corporis dolores excepturi. Libero laboriosam
                        sint et id nulla tenetur. Suscipit aut voluptate.</p>

                    <div class="icon-box">
                        <div class="icon"><i class="bx bx-fingerprint"></i></div>
                        <h4 class="title"><a href="#">Lorem Ipsum</a></h4>
                        <p class="description">Voluptatum deleniti atque corrupti quos dolores et quas molestias
                            excepturi sint occaecati cupiditate non provident</p>
                    </div>

                    <div class="icon-box">
                        <div class="icon"><i class="bx bx-gift"></i></div>
                        <h4 class="title"><a href="#">Nemo Enim</a></h4>
                        <p class="description">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis
                            praesentium voluptatum deleniti atque</p>
                    </div>

                    <div class="icon-box">
                        <div class="icon"><i class="bx bx-atom"></i></div>
                        <h4 class="title"><a href="#">Dine Pad</a></h4>
                        <p class="description">Explicabo est voluptatum asperiores consequatur magnam. Et veritatis
                            odit. Sunt aut deserunt minus aut eligendi omnis</p>
                    </div>

                </div>
            </div>

        </div>
    </section>
    {% include 'med/footer.html' %}
{% endblock %}

templates/med/appoint.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    {% include 'topbar.html' %}
    <header id="header" class="fixed-top">
        <div class="container d-flex align-items-center">
            <h1 class="logo me-auto"><a href="{% url 'med:home' %}" class="logo me-auto"><img
                    src="{% static 'assets/img/favicon1.png' %}" alt="" class="img-fluid"> Medilab</a></h1>
            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul>
                    {% if request.user.is_authenticated %}
                        <li><a class="nav-link scrollto" href="{% url 'med:acceptance' %}">Qabul</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:bemor' %}">Bemor</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:create-patient' %}">Bemor Qo'shish</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:logout' %}">Logout</a></li>
                    {% else %}
                        <li><a class="nav-link scrollto" href="{% url 'med:home' %}">Home</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:about' %}">About</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:services' %}">Services</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:department' %}">Departments</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:doctor' %}">Doctors</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:contact' %}">Contact</a></li>
                        <li><a href="{% url 'med:appoint' %}" class="nav-link scrollto active"><span
                                class="d-none d-md-inline">Make an Appointment</span>
                        </a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:login' %}">Login</a></li>
                    {% endif %}
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav>
        </div>
    </header>
    <br><br><br><br>
    {% load crispy_forms_tags %}
    <section id="hero" class="d-flex align-items-center">
        <div class="container">
            <h1>Hush kelibsiz!</h1>
            <h2>Qabulga yozilishni hohlaysizmi?</h2>
            <button type="button" class="btn-get-started scrollto" data-bs-toggle="modal" data-bs-target="#exampleModal"
                    data-bs-whatever="@mdo">Qabulga yozilish
            </button>
        </div>
    </section>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Qabulga yozilish</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Saqlash</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
    <footer id="footer">

        <div class="footer-top">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-md-6 footer-contact">
                        <h3>Medilab</h3>
                        <p>
                            A108 Adam Street <br>
                            New York, NY 535022<br>
                            United States <br><br>
                            <strong>Phone:</strong> +1 5589 55488 55<br>
                            <strong>Email:</strong> info@example.com<br>
                        </p>
                    </div>

                    <div class="col-lg-2 col-md-6 footer-links">
                        <h4>Useful Links</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>Our Services</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-4 col-md-6 footer-newsletter">
                        <h4>Join Our Newsletter</h4>
                        <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
                        <form action="" method="post">
                            <input type="email" name="email"><input type="submit" value="Subscribe">
                        </form>
                    </div>

                </div>
            </div>
        </div>

        <div class="container d-md-flex py-4">

            <div class="me-md-auto text-center text-md-start">
                <div class="copyright">
                    &copy; Copyright <strong><span>Medilab</span></strong>. All Rights Reserved
                </div>
                <div class="credits">
                    <!-- All the links in the footer should remain intact. -->
                    <!-- You can delete the links only if you purchased the pro version. -->
                    <!-- Licensing information: https://bootstrapmade.com/license/ -->
                    <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/medilab-free-medical-bootstrap-theme/ -->
                    Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
                </div>
            </div>
            <div class="social-links text-center text-md-right pt-3 pt-md-0">
                <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
            </div>
        </div>
    </footer>
    <div id="preloader"></div>
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>
{% endblock %}

templates/med/contact.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    {% include 'topbar.html' %}
    <header id="header" class="fixed-top">
        <div class="container d-flex align-items-center">
            <h1 class="logo me-auto"><a href="{% url 'med:home' %}" class="logo me-auto"><img
                    src="{% static 'assets/img/favicon1.png' %}" alt="" class="img-fluid"> Medilab</a></h1>
            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul>
                    {% if request.user.is_authenticated %}
                        <li><a class="nav-link scrollto" href="{% url 'med:acceptance' %}">Qabul</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:bemor' %}">Bemor</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:create-patient' %}">Bemor Qo'shish</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:logout' %}">Logout</a></li>
                    {% else %}
                        <li><a class="nav-link scrollto" href="{% url 'med:home' %}">Home</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:about' %}">About</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:services' %}">Services</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:department' %}">Departments</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:doctor' %}">Doctors</a></li>
                        <li><a class="nav-link scrollto active" href="{% url 'med:contact' %}">Contact</a></li>
                        <li><a href="{% url 'med:appoint' %}" class="nav-link scrollto"><span
                                class="d-none d-md-inline">Make an Appointment</span>
                        </a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:login' %}">Login</a></li>
                    {% endif %}
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav>
        </div>
    </header>
    <br><br><br>br
    <section id="contact" class="contact">
        <div class="container">
            <div class="section-title">
                <h2>Contact</h2>
                <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit
                    sint
                    consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea.
                    Quia
                    fugiat sit in iste officiis commodi quidem hic quas.</p>
            </div>
        </div>
        <div>
            <iframe style="border:0; width: 100%; height: 350px;"
                    src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12097.433213460943!2d-74.0062269!3d40.7101282!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb89d1fe6bc499443!2sDowntown+Conference+Center!5e0!3m2!1smk!2sbg!4v1539943755621"
                    frameborder="0" allowfullscreen></iframe>
        </div>
        <div class="container">
            <div class="row mt-5">
                <div class="col-lg-4">
                    <div class="info">
                        <div class="address">
                            <i class="bi bi-geo-alt"></i>
                            <h4>Location:</h4>
                            <p>Uzbekiston Toshkent</p>
                        </div>
                        <div class="email">
                            <i class="bi bi-envelope"></i>
                            <h4>Email:</h4>
                            <p>sayfullayevbekzod465@gmail.com</p>
                        </div>
                        <div class="phone">
                            <i class="bi bi-phone"></i>
                            <h4>Call:</h4>
                            <p>+998(93)594-01-35</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-8 mt-5 mt-lg-0">
                    <form action="forms/contact.php" method="post" role="form" class="php-email-form">
                        <div class="row">
                            <div class="col-md-6 form-group">
                                <input type="text" name="name" class="form-control" id="name"
                                       placeholder="Your Name"
                                       required>
                            </div>
                            <div class="col-md-6 form-group mt-3 mt-md-0">
                                <input type="email" class="form-control" name="email" id="email"
                                       placeholder="Your Email" required>
                            </div>
                        </div>
                        <div class="form-group mt-3">
                            <input type="text" class="form-control" name="subject" id="subject"
                                   placeholder="Subject"
                                   required>
                        </div>
                        <div class="form-group mt-3">
                            <textarea class="form-control" name="message" rows="5" placeholder="Message"
                                      required></textarea>
                        </div>
                        <div class="my-3">
                            <div class="loading">Loading</div>
                            <div class="error-message"></div>
                            <div class="sent-message">Your message has been sent. Thank you!</div>
                        </div>
                        <div class="text-center">
                            <button type="submit">Send Message</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    {% include 'med/footer.html' %}
{% endblock %}

templates/med/departments.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    {% include 'topbar.html' %}
    <header id="header" class="fixed-top">
        <div class="container d-flex align-items-center">
            <h1 class="logo me-auto"><a href="{% url 'med:home' %}" class="logo me-auto"><img
                    src="{% static 'assets/img/favicon1.png' %}" alt="" class="img-fluid"> Medilab</a></h1>
            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul>
                    {% if request.user.is_authenticated %}
                        <li><a class="nav-link scrollto" href="{% url 'med:acceptance' %}">Qabul</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:bemor' %}">Bemor</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:create-patient' %}">Bemor Qo'shish</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:logout' %}">Logout</a></li>
                    {% else %}
                        <li><a class="nav-link scrollto" href="{% url 'med:home' %}">Home</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:about' %}">About</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:services' %}">Services</a></li>
                        <li><a class="nav-link scrollto active" href="{% url 'med:department' %}">Departments</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:doctor' %}">Doctors</a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:contact' %}">Contact</a></li>
                        <li><a href="{% url 'med:appoint' %}" class="nav-link scrollto"><span
                                class="d-none d-md-inline">Make an Appointment</span>
                        </a></li>
                        <li><a class="nav-link scrollto" href="{% url 'med:login' %}">Login</a></li>
                    {% endif %}
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav>
        </div>
    </header>
    <br><br><br><br>
    <section id="departments" class="departments">
        <div class="container">

            <div class="section-title">
                <h2>Departments</h2>
                <p>Magnam dolores commodi suscipit. Necessitatibus eius consequatur ex aliquid fuga eum quidem. Sit
                    sint
                    consectetur velit. Quisquam quos quisquam cupiditate. Et nemo qui impedit suscipit alias ea.
                    Quia
                    fugiat sit in iste officiis commodi quidem hic quas.</p>
            </div>
            <div class="accordion" id="accordionExample">
                <div class="accordion" id="accordionExample">
                    {% for d in departments %}
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="heading{{ loop.index }}">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                        data-bs-target="#collapse{{ loop.index }}" aria-expanded="true"
                                        aria-controls="collapse{{ loop.index }}">
                                    {{ d.title }}
                                </button>
                            </h2>
                            <div id="collapse{{ loop.index }}" class="accordion-collapse collapse"
                                 aria-labelledby="heading{{ loop.index }}"
                                 data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    <strong>{{ d.description }}</strong> {{ d.body }}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"
            integrity="sha384-p3G1YQk5CtK9vO6P4OgiDFsZULzRMJ8OweD7d1eMk9PTQQ3aIVbvpb+5GtfvY8C5"
            crossorigin="anonymous"></script>
    {% include 'med/footer.html' %}
{% endblock %}

templates/topbar.html
<div id="topbar" class="d-flex align-items-center fixed-top">
    <div class="container d-flex justify-content-between">
        <div class="contact-info d-flex align-items-center">
            <i class="bi bi-envelope"></i> <a href="mailto:sayfullayevbekzod1234@gmail.com">sayfullayevbekzod1234@gmail.com</a>
            <i class="bi bi-phone"></i><a href="tel:+998(93)594-01-35">+998(93)594-01-35</a>
        </div>
        <div class="d-none d-lg-flex social-links align-items-center">
            <a href="https://www.instagram.com/_sayful1ayev_/" class="instagram"><i class="bi bi-instagram"></i></a>
            <a href="https://www.linkedin.com/in/bekzod-sayfullayev-4348512a3/" class="linkedin"><i
                    class="bi bi-linkedin"></i></a>
        </div>
    </div>
</div>